export const albumQuizData = [
        {
          questionImage: "./album covers/01.png", // Clear image for question
          answerImage: "./album covers/01_patti smith.png", // Clear image for answer
          artist: "Patti Smith",
          album: "Horses",
          hint: "P _ _ _ _  S _ _ _ _",
        },
        {
          questionImage: "./album covers/02.png",
          answerImage: "./album covers/02_the notorious big.png",
          artist: "The Notorious Big",
          album: "Ready to Die",
          hint: "The N _ _ _ _ _ _ _ _  B _ _",
        },
        {
          questionImage: "./album covers/03.png",
          answerImage: "./album covers/03_led zeppelin.png",
          artist: "Led Zeppelin",
          album: "Led Zeppelin IV, 1969",
          hint: "L _ _  Z _ _ _ _ _ _ _",
        },
        {
          questionImage: "./album covers/04.png",
          answerImage: "./album covers/04_pink floyd.png",
          artist: "Pink Floyd",
          album: "The Dark Side of the Moon, 1973",
          hint: "P _ _ _  F _ _ _ _",
        },
        {
          questionImage: "./album covers/05.png",
          answerImage: "./album covers/05_cyndi lauper.png",
          artist: "Cyndi Lauper",
          album: "She's So Unusual, 1983",
          hint: "C _ _ _ _  L _ _ _ _ _",
        },
        {
          questionImage: "./album covers/06.png",
          answerImage: "./album covers/06_igor nikolaev natasha koroleva.png",
          artist: "Игорь Николаев Наташа Королёва",
          album: "Дельфин и русалка",
          hint: "Дельфин и русалка",
        },
        {
          questionImage: "./album covers/07.png",
          answerImage: "./album covers/07_public enemy.png",
          artist: "Public Enemy",
          album: "Fear of a Black Planet",
          hint: "P _ _ _ _ _  E _ _ _ _",
        },
        {
          questionImage: "./album covers/08.png",
          answerImage: "./album covers/08_the beatles.png",
          artist: "The Beatles",
          album: "Sgt. Pepper's Lonely Hearts Club Band",
          hint: "The B _ _ _ _ _ _",
        },
        {
          questionImage: "./album covers/09.png",
          answerImage: "./album covers/09_hole.png",
          artist: "Hole",
          album: "Live Through This",
          hint: "H _ _ _",
        },
        {
          questionImage: "./album covers/10.png",
          answerImage: "./album covers/10_kendrick lamar.png",
          artist: "Kendrick Lamar",
          album: "To Pimp a Butterfly",
          hint: "K _ _ _ _ _ _ _  L _ _ _ _",
        },
        {
          questionImage: "./album covers/11.png",
          answerImage: "./album covers/11_blink 182.png",
          artist: "Blink 182",
          album: "Enema of the State, 1999",
          hint: "B _ _ _ _  182",
        },
        {
          questionImage: "./album covers/12.png",
          answerImage: "./album covers/12_the clash.png",
          artist: "The Clash",
          album: "London Calling, 1979",
          hint: "L _ _ _ _ _  C _ _ _ _ _ _",
        },
        {
          questionImage: "./album covers/13.png",
          answerImage: "./album covers/13_santana.png",
          artist: "Santana",
          album: "Abraxas,1970",
          hint: "A _ _ _ _ _ _",
        },
        {
          questionImage: "./album covers/14.png",
          answerImage: "./album covers/14_judas priest.png",
          artist: "Judas Priest",
          album: "British Steel, 1980",
          hint: "J _ _ _ _  P _ _ _ _ _",
        },
      ];